### ISSUE TITLE
userId not saved @ Collection

### ISSUE THREAD

**Issue by fdddk23** [yogiben/meteor-autoform-file#101]
The userid isn't saved @ the filrecord colleciton.
But it should save it?
Or not?

**Comment by RamyElkest** [comment]
I believe so, under owner

<pre>
meteor:PRIMARY> db.cfs.sounds.filerecord.findOne()
{
    "_id" : "8YFQYrRZtRqt5uLti",
    "original" : {
        "name" : "meteor",
        "updatedAt" : ISODate("2015-10-27T00:16:39Z"),
        "size" : 4910,
        "type" : ""
    },
    "owner" : "a3xTXLfHXPBKhszsz",
    "uploadedAt" : ISODate("2016-01-31T02:14:08.599Z"),
    "copies" : {
        "sounds" : {
            "name" : "meteor",
            "type" : "",
            "size" : 4910,
            "key" : "56ad718cf75ca4d52834d83a",
            "updatedAt" : ISODate("2016-01-31T02:29:32.623Z"),
            "createdAt" : ISODate("2016-01-31T02:29:32.623Z")
        }
    }
}
</pre>

**Comment by fdddk23** [comment]
ok - for me no owner is created :(
But i'm already not using this package anymore
Neverthless thanks!
