### ISSUE TITLE
How to display images 

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-autoform-file#11]
How can i display the images that i have uploaded?

BTW: nice package!

**Comment by djhi** [comment]
Check `cfs` documentation, this is the package responsible for that. `meteor-autoform-file` only handle the upload for `autoform`.

You may like `cfs-ui`: https://github.com/CollectionFS/Meteor-cfs-ui

**Comment by yogiben** [comment]
Yes, that's correct.
