### ISSUE TITLE
FR: multiple upload

### ISSUE THREAD

**Issue by aj07mm** [yogiben/meteor-autoform-file#12]
im trying to create multiple inputs to upload images, but when i try to instantiate a autoform it gives me String inputs, not image inputs.

```
"photoGallery": {
		type: [String],
		label: "Bus - photo gallery",
		optional: true,
		autoform:{
			afFieldInput:{
				type: 'fileUpload',
                collection: 'Images'
			}
		}
	}

{{> afQuickField name='photoGallery' }}

```

is that currently possible?

**Comment by yogiben** [comment]
Right now, that's not currently possible.

**Comment by peernohell** [comment]
You can try this, it's work for me

```javascript
"photoGallery": {
        type: [String],
        label: "Bus - photo gallery",
        optional: true
    },
 "photoGallery.$": {
        autoform:{
            afFieldInput:{
                type: 'fileUpload',
                collection: 'Images'
            }
        }
  }
```

**Comment by jfols** [comment]
@peernohell :+1: 
@yogiben perhaps you could add this helpful info to the readme? If you'd like I could submit a quick PR.

**Comment by peernohell** [comment]
@jfols yes greate idee. I will submit a PR for the readme :)

**Comment by jessaimaya** [comment]
@peernohell :D :+1
