### ISSUE TITLE
UX detail - filename displayed when no image is uploaded

### ISSUE THREAD

**Issue by tintoverano** [yogiben/meteor-autoform-file#14]
hi,

is there any way to display the short file name: "Capture_Drop_Down.xlsx"  instead of 

````
/cfs/files/patientFiles/6AALn5zQxwaes35do/Capture_Drop_Down.xlsx?token=eyJhdXRoVG9rZW4iOiJWUzhJcThmbkJGcWxBWmFMTzFQMFNZLW1fdGlCeENNb2dUMDhVRi1iZ0J5In0%3D"?
````

clicking on the name nothing happens, is it a bug?

thanks for your support!

regards,

tinto

**Comment by yogiben** [comment]
Yes, it looks like a bug. This is when you're updating a doc, right?

**Comment by tintoverano** [comment]
yes, this text gets displayed when the pict is shown in the 'name' field of the form

**Comment by ddresch** [comment]
I've seeing the same behavior additionally I get this error message:

    Exception in template helper: TypeError: undefined is not a function at      
    Object.Template.afFileUpload.helpers.fileUpload

On 'insert' and 'update' of a doc - makes no difference error is showing up. 

I guess the point is this line:

    collection.findOne({_id:file}).name() (autoform-file.coffee - line 118)

'collection' is a String not an Object when it's passed to the function?

**Comment by tintoverano** [comment]
I had this error as well, after downloading the package and adding it as local the error was gone

I had no time yet to go after the problem though

**Comment by ddresch** [comment]
OK with the local copy it's working with images but still other filetypes are displayed like this:

    /cfs/files/patientFiles/6AALn5zQxwaes35do/Capture_Drop_Down.xlsx?token=eyJhdXRoVG9rZW4iOiJWUzhJcThmbkJGcWxBWmFMTzFQMFNZLW1fdGlCeENNb2dUMDhVRi1iZ0J5In0%3D"?

The problem with the 'collection' is 'fixed' in this version, is there another version live in the atmosphere repo? Was the problem with other filetypes also fixed on your side?

**Comment by tintoverano** [comment]
yes, the long filename stays even then, but that could be fixed just takes time

**Comment by jfols** [comment]
I've got a fix for this https://github.com/modweb/meteor-autoform-file/commit/38618bfb43d6149d233a4f87274d4b963544cf7d
I'll make a PR after my open PR #19 gets sorted :smile:

**Comment by ddresch** [comment]
@jfols thanks for this patch and your open PR #19 - I added it manually and it's working on my side too. Just wanted to confirm :)

**Comment by jfols** [comment]
@ddresch cool, so is PR #19 good to merge then?
