### ISSUE TITLE
[Idea] Callback before insertion

### ISSUE THREAD

**Issue by RobertLowe** [yogiben/meteor-autoform-file#18]
https://github.com/yogiben/meteor-autoform-file/blob/master/lib/client/autoform-file.coffee#L67

It would be nice to have a callback before insert so be can configure `metadata` for instance. Useful if we want to associate an `ownerId` with a file for example.

**Comment by adriamooney** [comment]
Yes, I need this too!

**Comment by Tycale** [comment]
+1

**Comment by mpowaga** [comment]
Implemented in fc3ca05344f5.
