### ISSUE TITLE
It doesn't seem to work with cfs-s3

### ISSUE THREAD

**Issue by taromero** [yogiben/meteor-autoform-file#25]
I could use this package with cfs-grid, but when I tried to transition to cfs-s3, it throws an error when selecting a file to upload:

```
PUT http://localhost:3000/cfs/files/files/i5JrZ4kbZQkoYcNJc?chunk=0&filename=ca…VG9rZW4iOiI3RVlOcUxQclVVcnJldDY2NGpSdDh1TVdlTl9Sdl9OLS01Vlp2MnVxNjIyIn0%3D 503 (Service Unavailable) at http-call-client.js:198
```

```
 Error: "Queue" failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: FS.TempStore.Storage is not set: Install cfs:filesystem or cfs:gridfs or set it manually     at mount... [undefined], Error: failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: FS.TempStore.Storage is not set: Install cfs:filesystem or cfs:gridfs or set it manually     at mount... [undefined]
    at upload-http-client.js:33
    at http-call-client.js:69
    at _.once (underscore.js:750)
    at XMLHttpRequest.xhr.onreadystatechange (http-call-client.js:192)
```

Any idea why? is this package designed to work with cfs-s3?

**Comment by djhi** [comment]
As stated in the error, you currently must install either  `cfs:filesystem` or `cfs:gridfs` to use `cfs:s3`.

But, even with this, I haven't been able to use the s3 package yet. Looks like they are working on it and it is unstable, as stated [here](https://github.com/CollectionFS/Meteor-CollectionFS/tree/master/packages/s3)

> NOTE: This package is under active development right now (2014-5-12). It has bugs and the API may continue to change. Please help test it and fix bugs, but don't use in production yet.

**Comment by taromero** [comment]
Right, I tried adding them too, with no result.

I finally used https://github.com/CulturalMe/meteor-slingshot (which doesn't support autoform).

**Comment by Igor1201** [comment]
I'm using `cfs:s3` without issues, with it and `cfs:filesystem` and `cfs:standard-packages` in my project.
The only "issue" is that every time I'm uploading a file, console logs the following warning: 
```
http-call-client.js:101 The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType.
```
But that is a `cfs:upload-http` warning, as stated on their file.

**Comment by obiwarn** [comment]
@Igor1201 same issue here. any way to remove it?

**Comment by mpowaga** [comment]
@obiwarn I'm afraid it can't be done without touching `cfs:upload-http` package. You can follow this [issue](https://github.com/CollectionFS/Meteor-CollectionFS/issues/688).
