### ISSUE TITLE
remove data 

### ISSUE THREAD

**Issue by YouSour** [yogiben/meteor-autoform-file#41]
hi , i'm new here , how can i remove data in database ? thank you for advance .

**Comment by mpowaga** [comment]
You can read CollectionFS [docs](https://github.com/CollectionFS/Meteor-CollectionFS).

Using example in meteor-autoform-file you can do it like this:

```javascript
var pictureId = Posts.findOne().picture;
Images.remove(pictureId);
```

**Comment by YouSour** [comment]
hi , could you give example more clearly ?
here example code i want  :
js:
-------
'click .remove': function () {
// remove file image 
    },


collection
---
Images = new FS.Collection('images', {
    stores: [new FS.Store.GridFS("images", {})]
});

Images.allow({
    insert: function (userId, doc) {
        return true;
    },
    download: function (userId) {
        return true;
    },
    remove: function (userId) {
        return true;
    }
});
