### ISSUE TITLE
show uploaded file during form update

### ISSUE THREAD

**Issue by amit1911** [yogiben/meteor-autoform-file#43]
I am trying to show the current uploaded files for the form when the user tries to update the form. How do i do that?
![screen shot 2015-06-13 at 6 03 06 pm](https://cloud.githubusercontent.com/assets/3509404/8143905/91f070b4-11f6-11e5-9529-c39817c92134.png)

**Comment by mpowaga** [comment]
Do you want to mark currently uploaded files (i.e. make them look different than files to be changed)?

**Comment by amit1911** [comment]
no basically i have a form where users can upload files. So later i am trying to provide an update feature where they can view their currently uploaded files and edit them(remove previous files/ add new ones) just like in the image attached above.
