### ISSUE TITLE
Block autoform submission while uploading files

### ISSUE THREAD

**Issue by Igor1201** [yogiben/meteor-autoform-file#44]
With the latest commit (636a2a0a856209710b080fe776494ffb38da8e3c), it shows "Uploading..." while the file is uploading, but we can submit the autoform that's holding the plugin, not saving the file id and messing up with everything.

It would be nice if we could prevent that form submission. Maybe setting a flag on each instance and stopping form submission event propagation if that flag is set on "uploading"?

**Comment by mpowaga** [comment]
For me it works. Maybe something specific to your code? Can you provide steps to reproduce?
