### ISSUE TITLE
Broken when using cordova?

### ISSUE THREAD

**Issue by sschuchlenz** [yogiben/meteor-autoform-file#47]
When implementing your file uploads in my meteor app, everything works fine so far but once I deploy my app to mobile (Android) devices, clicking the upload button doesn't do anything. Is meteor-autoform-file not intended to be used on cordova based mobile apps?

**Comment by sschuchlenz** [comment]
Update: it is also broken in Safari, at least Windows and Linux versions (don't have a Mac at hand to test it there).

**Comment by mpowaga** [comment]
Newest version uses jquery fileupload which works on Safari.
