### ISSUE TITLE
Publish uploading file without overpublishing

### ISSUE THREAD

**Issue by Neobii** [yogiben/meteor-autoform-file#51]
Files need to be published automatically that are being uploaded because overpublishing will of course publish a lot of unnecessary data.

**Comment by serkandurusoy** [comment]
Hm, actually I was wondering the same thing.

Are there any best practices or patterns to ensure we publish just enough for the uploads to work?

Otherwise, publishing the whole store is a bad idea for many reasons.

**Comment by Tycale** [comment]
I think that an extra field "owner" could do the job. We need #18 :+1:

**Comment by Tycale** [comment]
You can use the owner field :
https://github.com/yogiben/meteor-autoform-file/blob/master/lib/client/autoform-file.coffee#L58

    Meteor.publish 'publishName', ->
      collection.find({owner: @userId})

**Comment by mpowaga** [comment]
Uploaded file will be automatically published by autoform-file. Is that not working for you?

**Comment by serkandurusoy** [comment]
@Tycale that would still publish all the files belonging to a user.

@mpowaga I don't understand what you mean. If I don't publish the collection manually, I can't see the uploaded image file on the insert form.

**Comment by Tycale** [comment]
Yes, you're right.
In fact, it works now without "publish/subscribe".
I use Meteor-starter and I had to change manually the version of this packet from 0.2.7 to 0.2.9.
