### ISSUE TITLE
If form or page has more than one upload field

### ISSUE THREAD

**Issue by rclai** [yogiben/meteor-autoform-file#52]
[This line of code](https://github.com/yogiben/meteor-autoform-file/blob/master/lib/client/autoform-file.coffee#L21) is not going work. This only works when there's only one upload field present at a time.

**Comment by mpowaga** [comment]
Can you provide an example? It's template level subscription so it should work as each field is separate instance.

**Comment by rclai** [comment]
Yeah but it's the same subscription name. You can't run multiple identical subscriptions at the same time.
