### ISSUE TITLE
Wrong Version Published to Atmosphere?

### ISSUE THREAD

**Issue by abernix** [yogiben/meteor-autoform-file#53]
Having a bit of an issue figuring out what's up with the version of this package right now.  Seems like something is out of sync somewhere, assuming that we're working off the `master` branch and not `develop` (which had a version bump recently, but not sure why?).

**tl;dr:** I think the `develop` branch might have accidentally got version-bumped and pushed to atmosphere.

```bash
abernix@host:~/Dev/Project (master)$ meteor update
yogiben:autoform-file               0.2.7* File upload for AutoForm
                                              
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further, try typing
  `meteor add <package>@<newVersion>` to see more information.
```
So, after an `meteor update`, it's still there, saying there's an upgrade... Okay, let's see what's up - the git repo `master` branch just got a bump to `0.2.8`, so...
```bash
abernix@host:~/Dev/Project (master)$ meteor add yogiben:autoform-file@0.2.8
 => Errors while parsing arguments:           
                                              
While adding package yogiben:autoform-file@0.2.8:
error: no such version yogiben:autoform-file@0.2.8
```
Hmm... `no such version` 0.2.8?  Let's look at Atmosphere... 

<img width="379" alt="screen shot 2015-08-01 at 10 02 39 pm" src="https://cloud.githubusercontent.com/assets/841294/9023185/ce0ba11c-3899-11e5-9806-bc90d8b060d9.png">

Ok, looks like a weird jump from **0.2.7** to **1.0.1**... but I'll try it...

```bash
abernix@host:~/Dev/Project (master)$ meteor add yogiben:autoform-file@1.0.1
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint aldeed:autoform@4.0.2 is not satisfied by aldeed:autoform 5.3.2.
Constraints on package "aldeed:autoform":
* aldeed:autoform@5.3.2 <- abernix:autoform-semantic-ui 0.4.5
* aldeed:autoform@4.0.2 <- yogiben:autoform-file 1.0.1
```
Yea... something seems out of pitch.  Did the `develop` branch get accidentally bumped and published to atmosphere? :eyes:

**Comment by mpowaga** [comment]
That seems to be an accident definitely :)
