### ISSUE TITLE
less 2.5.0 compatibility

### ISSUE THREAD

**Issue by scsirdx** [yogiben/meteor-autoform-file#56]
Hello!

I tried to install yogiben:autoform-file in meteor 1.2-rc.7, but got message about less package:

meteor add yogiben:autoform-file
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0-rc.2_1.
Constraints on package "less":
* less@=2.5.0-rc.2_1 <- top level
* less@1.0.11 <- yogiben:autoform-file 0.2.9

Maybe it's possible to detect meteor version in package.js and change required less version?

**Comment by teknologist** [comment]
+1

**Comment by carlosbaraza** [comment]
+1

**Comment by Neobii** [comment]
+1

**Comment by jackkav** [comment]
+1

**Comment by miri-am** [comment]
+1

**Comment by kristijanbambir** [comment]
+1

**Comment by CaptainN** [comment]
Pull Request #65 addresses this.

**Comment by Kostanos** [comment]
+1
