### ISSUE TITLE
how to change default uploaded label

### ISSUE THREAD

**Issue by foxeverfox** [yogiben/meteor-autoform-file#58]
hi  ,

i love this package , it working as expected when working with image upload , but it seem i cant change the label when working with non image files  , eg: pdf
it always show "/cfs/files/blabla" after i choose file to upload.

is there anyway i can customize what to show on that label?

thanks for help and great package .

**Comment by mpowaga** [comment]
You can specify your [custom preview template](https://github.com/yogiben/meteor-autoform-file#custom-file-preview).
