### ISSUE TITLE
Unable to update...

### ISSUE THREAD

**Issue by vimes1984** [yogiben/meteor-autoform-file#59]
When using a autoform to update a collection like so: 
  {{> quickForm collection="MediaCollection" doc=updateMediasingle id="updateMediaForm" type="update"}}

And defining a doc in a template helper: 
       Template.editmedia.helpers({
          updateMediasingle: function() {
            return MediaCollection.findOne({_id: $stateParams.mediaID});
          }
        });
I'm getting: 
Exception in template helper: TypeError: collection.findOne is not a function
    at Object.Template.afFileUpload.helpers.fileUpload /yogiben_autoform-file.js?:285:24)

It fails to load the image on first render but does load it after I hit submit on the update form..

**Comment by mpowaga** [comment]
Make sure that `MediaCollection` is defined in global scope. This seems to be a problem.
