### ISSUE TITLE
Constraint on package "less" preventing update to Meteor 1.2.0.1

### ISSUE THREAD

**Issue by kristijanbambir** [yogiben/meteor-autoform-file#64]
Update to Meteor 1.2.0.1 is failing due to conflicting LESS version. This is the full error message:

    $ meteor update
    Update to release METEOR@1.2.0.1 is impossible:
    While selecting package versions:             
    error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
    Constraints on package "less":
    * less@=2.5.0_2 <- top level
    * less@1.0.11 <- yogiben:autoform-file 0.2.9
    
    This project is at the latest release which is compatible with your current package constraints.
    Your top-level dependencies are at their latest compatible versions.
                                                  
    The following top-level dependencies were not updated to the very latest version available:
     * yogiben:autoform-file 0.2.9 (1.0.1 is available)
                                              
    Newer versions of the following indirect dependencies are available:
     * babrahams:editable-json 0.4.3 (0.6.0 is available)
     * meteorhacks:meteorx 1.0.2 (1.3.1 is available)
     * sanjo:karma 1.7.0 (2.0.0 is available)     
     * softwarerero:accounts-t9n 1.0.9 (1.1.4 is available)
    To update one or more of these packages, pass their names to `meteor update`.

Is there an immediate solution or does this package need to change its LESS dependency?

Edit: Actually a copy of [#56](https://github.com/yogiben/meteor-autoform-file/issues/56)

**Comment by Neobii** [comment]
You can clone this package into your /packages folder and change the meteor dependency to 1.2 inside the package.js.

**Comment by CaptainN** [comment]
Pull request #65 has the edit.

**Comment by CaptainN** [comment]
@MikeSmith12222 If you don't have a packages folder in the root of your project, create one, then download my fork and place it in that packages folder. Meteor will use the local package instead of the one in atmosphere. Whenever this is fixed in the live repo you can delete the local package. This will get it working for the short term.

**Comment by thearabbit** [comment]
I have the same problem.

**Comment by ko0stik** [comment]
Thank you @CaptainN, works like a charm. Also for those doing it the old (github) way and using git in their project, do not forget to remove the .git after you cloned it locally otherwise you'll just end up in git submodule hell :).
