### ISSUE TITLE
Upload preview/status not working

### ISSUE THREAD

**Issue by CaptainN** [yogiben/meteor-autoform-file#68]
I'm getting a silent failure when uploading after upgrading to Meteor 1.2. The upload does work (with `FS.debug = true;` I can see that it uploaded, and there are no errors reported - and the file does arrive in DropBox), but it doesn't show a progress bar, nor any indication that the file uploaded successfully. It also doesn't trigger the complete handlers.

**Comment by kristijanbambir** [comment]
+1

**Comment by CaptainN** [comment]
For anyone who needs this working now, you can use an older commit from before Bugfix, such as @2c74180 in your local packages directory.

**Comment by juniobranco** [comment]
Actually i tried that approach and it didnt work.

Somehow, if I just do a fork and convert from .coffee to a .js (the client side) It actually resolves the problem without any actual code changes. This is quite intriguing..

**Comment by isubasti** [comment]
@juniobranco Notice that there is a bugfix: https://github.com/yogiben/meteor-autoform-file/commit/85ace6826a9168c16d71539caea226ef5ac19496 which fix the problem but no new package has been released to atmosphere.js.

**Comment by juniobranco** [comment]
thanks @isubasti  completly missed that, I assumed it was in sync with atmosphere. Thanks for the heads up.
