### ISSUE TITLE
Error:  "The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType."?

### ISSUE THREAD

**Issue by thearabbit** [yogiben/meteor-autoform-file#69]
I try to update to new version, but don't work:
```js
The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
```

**Comment by ivansglazunov** [comment]
+1
Some problem in: `cfs_upload-http.js:109`

**Comment by thsowers** [comment]
+1 Same error message

**Comment by isubasti** [comment]
Tried it out and yes it does give a warning but not really an error, the file will still be uploaded but the last few commits breaks the progress bar and preview which gives an impression that the file is not properly uploaded. Refer to https://github.com/yogiben/meteor-autoform-file/issues/68#issuecomment-146896947 for a temporary fix.

**Comment by Xiangshen-Meng** [comment]
+1
The file is uploaded, but no preview and process bar.
And can't save the file info to collection when submit the form.

**Comment by gwendall** [comment]
+1

**Comment by veslo1** [comment]
+1

**Comment by mrrfox** [comment]
+1

**Comment by rizkysyazuli** [comment]
same with #49

**Comment by thearabbit** [comment]
I just do a fork and convert from .coffee to a .js (the client side) It actually resolves the problem without any actual code changes like [#68 (comment)](https://github.com/yogiben/meteor-autoform-file/issues/68#issuecomment-146896947)

**Comment by isubasti** [comment]
Notice that there is a bugfix: https://github.com/yogiben/meteor-autoform-file/commit/85ace6826a9168c16d71539caea226ef5ac19496 which fix the problem but no new package has been released to atmosphere.js

**Comment by rizkysyazuli** [comment]
@isubasti so do you suggest we install this package locally?

**Comment by gdw2** [comment]
I installed the package locally (from Xiangshen-Meng's branch, since it has the fix) and it works well.

**Comment by Xiangshen-Meng** [comment]
@mpowaga Sorry to disturb you. but when will the package be ready for the next version? seems it not works well currently.

**Comment by sachinkrishna** [comment]
I have tried to install a local version from Xiangshen-Meng's branch. But no luck. @Xiangshen-Meng @gdw2  any idea ?

HTTP uploadFile
fsFile-common.js:233 GET FILERECORD: undefined
fsFile-common.js:258 UPDATE: {"$set":{"chunkSize":2097152,"chunkCount":0,"chunkSum":1}}
upload-http-client.js:16 uploading chunk 0, bytes 0 to 31675 of 31675
upload-http-client.js:22 PUT to URL /cfs/files/images Object {filename: "chev1.jpg", token: "eyJhdXRoVG9rZW4iOiI5Qm4yQUtTR09kMmozUEVrYm96cUMxZS1oaktkWmNPVGE3LXduSWRrQ1NfIn0="}
http-call-client.js:101 The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.

**Comment by jwktje** [comment]
+1 same problem. Would love this to be fixed.

**Comment by sachinkrishna** [comment]
For me, the problem was using GroundDB. Not actually using it, but I had that package installed. Uninstalled the package and that fixed the issue.

**Comment by singularityhacker** [comment]
Two solid days of troubleshooting and I still can't get Meteor to upload text files.
"The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType" error in cfs_upload-http.js. Judging from peoples comments online, this is just broken right now.

**Comment by sachinkrishna** [comment]
You should really try your luck by removing packages individually and find if any of them is causing the issue. As i mentioned earlier, it was the grounddb package for me. 

[ Also, do you have FS.debug = true ? if so copy paste the console log too, that may help to better understand the situation ]

**Comment by jwktje** [comment]
This is what I'm getting:
<img width="1223" alt="screen shot 2015-11-11 at 18 21 13" src="https://cloud.githubusercontent.com/assets/4722137/11097699/07556294-88a1-11e5-868d-9ffdd4fd28cd.png">

**Comment by isubasti** [comment]
try using a custom template as discussed on https://github.com/yogiben/meteor-autoform-file/issues/74 .

**Comment by THPubs** [comment]
+1

**Comment by jwktje** [comment]
I fixed this by downloading this github repo and adding it to the local "packages" folder in my project.
It seems like it's only the atmosphere version that doesn't work.

**Comment by projectn00b** [comment]
This error directly hurts mobile uploads.

**Comment by THPubs** [comment]
@jwktje Im not so sure but looks like your solution works :-)

**Comment by jwktje** [comment]
@THPubs is does for me! I don't really like putting packages locally in my project but it's okay for now. It works for now, and once the fixed version makes it to Atmosphere I'll change it to that one again.

**Comment by THPubs** [comment]
Nope... looks like even the GitHub repo is not working for me. Have to select the file twice to get uploaded.

**Comment by NazarYablonskiy** [comment]
'meteor add coffeescript' resolves this problem

**Comment by jwktje** [comment]
Is this fixed? Only the workaround seems to help a little bit but I still have problems every now and again with the package. If we can help to solve this in any way, please let me know.

**Comment by beeekind** [comment]
This is not fixed.

**Comment by tuanhai12h** [comment]
Please review this issue, because it still happen :(
won't fixed

**Comment by ethereal517** [comment]
me too. 
It ruins progress bar, and I am using GroundDB, but I am not sure if it's because of GroundDB.

**Comment by THPubs** [comment]
@edvinsalo35 I don't think it's because of GroundDB... We are also having the same issue. I think you better build your own upload plugin or find an alternative. That's what I'm trying to do.

**Comment by FlawaCLV** [comment]
Not working for me either.
The warning prompts and the page reloads. My process is block.

**Comment by psibal** [comment]
Hi,
I am running into strange a issue.
Option 1- yogiben:autoform-file 
Initial upload image works, but for updates have to choose twice.

Option 2 - shinn:autoform-file
Initial upload image does not work, but for updates it works.

Any suggestion will be greatly appreciated.

Thanks
