### ISSUE TITLE
Error rendering field

### ISSUE THREAD

**Issue by sgelbart** [yogiben/meteor-autoform-file#7]
I'm trying to implement and having the error:
Unexpected object in htmljs in toText: [object Object]
It looks like might be related to what they were experienceing at autoform-bs-datepicker?
https://github.com/aldeed/meteor-autoform-bs-datepicker/issues/3
Might be something small on my part, thought I'd put it out there just incase...

**Comment by yogiben** [comment]
Cannot think why this would occur.

If in doubt, download my starter repo for a working version.

**Comment by mpowaga** [comment]
@sgelbart Can help if you provide the schema you using. Feel free to reopen.
