### ISSUE TITLE
Work without Autoform

### ISSUE THREAD

**Issue by ntoka** [yogiben/meteor-autoform-file#73]
Hello,

is it possible to make this plugin work without autoform?

**Comment by rikonor** [comment]
@ntoka, what are you trying to achieve?

The whole point of the plugin is to provide a file upload input for autoform.
If you're looking to upload files yourself, there is a nice tutorial on [The Meteor Chef](https://themeteorchef.com/recipes/uploading-files-to-amazon-s3) you could follow.
