### ISSUE TITLE
Metadata is not persisted

### ISSUE THREAD

**Issue by gerwinbrunner** [yogiben/meteor-autoform-file#76]
Hi,

I have the following simple Schema:
```
Schemas.documents = new SimpleSchema({
  govId: {
    type: String,
    autoform:{
      afFieldInput: {
        type: 'fileUpload',
        collection: 'docs',
        label: 'Choose file',
        onBeforeInsert: function() {
          return function(fileObj) {
            fileObj.enrollTempId = "Y1234";
            fileObj.metadata = fileObj.metadata || {};
            fileObj.metadata.enrollTempId = "X1235";
            console.log('fileObj', fileObj);
            //fileObj.name('picture.png');
            return fileObj;
          };
        }
      }
    }
  }
});
```
With the onBeforeInsert I want to add additional data to the Object in the collection.
The upload/insert of the file works nicely, but no metadata is added.

Do you have any idea what the problem could be?

Thanks,
Gerwin

**Comment by gerwinbrunner** [comment]
Anybody got an idea?

**Comment by zaklampert** [comment]
+1.

Just trying to console.log the object is not even working in onBeforeInsert

```
file: {
      type: String,
      optional: true,
      autoform:{
        afFieldInput:{
          type: 'fileUpload',
          collection:'Images',
          label:'Choose File',
          onBeforeInsert: function(){
            return function(fileObj){
              console.log(fileObj)
              return fileObj
            }
          }
        }
      }
    }
```

**Comment by derouck** [comment]
@gerwinbrunner It seems that you cannot add additional data in the onBeforeInsert. When you log the fileObj in onBeforeInsert and onAfterInsert you'll see that before the insert it is a File object. It's probably only possible to alter the real file data at that time, like e.g. filename.

If you want to add additional metadata you would have to look into the onAfterInsert hook. This plugin itself tried to add userId information by adding an extra owner property and even that is not working anymore. This would need to be done afterwards in an update of the Fs.File object which is given in the AfterInsert callback. So you would need to create an onAfterInsert like this which adds your metadata.

        afFieldInput: {
          type: "fileUpload",
          collection: "images",
          onAfterInsert: function() {
            return function(err, fileObj) {
              if (!err) {
                fileObj.update({$set: {metadata: {owner: Meteor.userId()}} });
                return fileObj;
              }
            };
          }
        }
  
In [this fix-branch](https://github.com/yogiben/meteor-autoform-file/commit/eea54b1b9dfc40e2d0f26b668d88d903f9cacbad) @yogiben does something similar to get the owner id in the metadata of the file. I don't know why it's not in master yet, as it seems the owner will not be stored for anyone with the version on the master branch. Maybe it's incompatible with older versions of collectionFS.

@zaklampert logging to console seems to work fine for me, is uploading working for you? Atmosphere is currently not in sync with github. For me only the latest github version works, so you might need to take that package local.

**Comment by bluxu** [comment]
Solved by adding `file = new FS.File(file)` at the top of the `_insert` function.

**Comment by mpowaga** [comment]
It used to work when metadata was stored on file obj before insert but it didn't work after some version of collectionfs. @derouck solution works fine and this way you can even override metadata set by autoform-file.
