### ISSUE TITLE
Can't add another file after removing one

### ISSUE THREAD

**Issue by bluxu** [yogiben/meteor-autoform-file#81]
The changed method on fileupload doesn't ever seem to fire more than once. Not sure why this happens - my use case is fairly complex so not trivial to create a MWE. Temporary fix is to grab the version of the package before it was migrated to jquery-fileupload, which still works fine.

**Comment by advany** [comment]
I have the same issue. After I create, I can't update. The fileupload doesn't fire anymore and now file is send to the server.

**Comment by jebarjonet** [comment]
Same issue. First upload is OK, removal is OK, but I can't add another file after that.

**Comment by jebarjonet** [comment]
It still does not work, same behavior

**Comment by mpowaga** [comment]
@jebarjonet Did you test with master branch? It's not deployed to Atmosphere yet.

**Comment by jebarjonet** [comment]
You are right ! My bad ! It is indeed not automatic. Waiting for the Atmosphere update :)
