### ISSUE TITLE
Conflicts with Less

### ISSUE THREAD

**Issue by leocrawf** [yogiben/meteor-autoform-file#84]
When I force an update using meteor yogiben:autoform-file@1.0.1 in the .meter/packages file I get:

Errors prevented startup:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.1.
Constraints on package "less":
- less@=2.5.1 <- top level
- less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
- less@1.0.11 <- yogiben:autoform-file 1.0.1

Conflict: Constraint aldeed:autoform@4.0.2 is not satisfied by aldeed:autoform 5.8.1.
Constraints on package "aldeed:autoform":
- aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datetimepicker 1.0.6
- aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datepicker 1.1.1
- aldeed:autoform@5.5.1 <- yogiben:autoform-modals 0.3.8
- aldeed:autoform@5.8.0 <- vazco:universe-autoform-select 0.1.20
- aldeed:autoform@4.0.2 <- yogiben:autoform-file 1.0.1
- aldeed:autoform@5.1.2 <- mpowaga:autoform-summernote 0.4.2

Your application has errors. Waiting for file change.

Any Idea how to resolve this.

**Comment by advany** [comment]
+1

**Comment by mpowaga** [comment]
You shouldn't force update to 1.0.1 as the latest version is 0.4.2. I know it's odd but this version was published by a mistake :)

**Comment by leocrawf** [comment]
So I have corrected this by fetching version 0.4.2 but only file upload works with no problem. I am not able to get before or after triggers or file preview and progress bar to work. Can someone point me in the right direction?
