### ISSUE TITLE
`Collection` should not be required as a string.

### ISSUE THREAD

**Issue by RobertLowe** [yogiben/meteor-autoform-file#9]
As of right now, `collection` is required to be a string and is looked up via `window`

https://github.com/yogiben/meteor-autoform-file/blob/master/lib/client/autoform-file.coffee#L68

We should be able to pass a `FS.Collection` object *or* the FS.Collection name, like in `cfs:autoform`. This is especially helpful when collections do not appear on the global namespace.

**Comment by yogiben** [comment]
Yes, I agree that should be implemented.
